name: Hidden Adventures Local
values:
  - key: rootUrl
    value: 'http://127.0.0.1:3000'
    enabled: true
  - key: baseUrl
    value: 'http://127.0.0.1:3000/api'
    enabled: true
  - key: publicAdventureId
    value: 3a64b684-1bb8-537c-851c-ac911a811735
    enabled: true
  - key: connectionsAdventureId
    value: 33e511cc-ecac-5966-8cdb-3314dec07d72
    enabled: true
  - key: profileHandle
    value: fixture_author
    enabled: true
  - key: connectedViewerToken
    value: 'local:connected_viewer'
    enabled: true
  - key: nonConnectedViewerToken
    value: 'local:non_connected_viewer'
    enabled: true
  - key: newUserToken
    value: 'local:new_user'
    enabled: true
  - key: desiredHandle
    value: fixture_new_handle
    enabled: true
  - key: limit
    value: '5'
    enabled: true
  - key: offset
    value: '0'
    enabled: true
