name: Hidden Adventures Local
values:
  - key: rootUrl
    value: 'http://127.0.0.1:3000'
    enabled: true
  - key: baseUrl
    value: 'http://127.0.0.1:3000/api'
    enabled: true
  - key: publicAdventureId
    value: fa89fa4a-9eac-5e1e-b9a1-70de0c1ad366
    enabled: true
  - key: connectionsAdventureId
    value: 4a37f341-68ae-5e2a-93cb-f23382477009
    enabled: true
  - key: profileHandle
    value: jacksanfil
    enabled: true
  - key: authToken
    value: REPLACE_WITH_COGNITO_ID_TOKEN
    enabled: true
  - key: desiredHandle
    value: freshslice1handle
    enabled: true
  - key: limit
    value: '5'
    enabled: true
  - key: offset
    value: '0'
    enabled: true
